### ISSUE TITLE
Add endpoint for rate-limits

### ISSUE THREAD

**Issue by kiblik** [mccutchen/go-httpbin#106]
It would be beneficial if there would be an available endpoint which implements rate limiting.

If too many requests would be sent to `/rate-limit`, the endpoint would return [`HTTP-429`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) with header [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After).

It would be useful for testing adaptive methods of limiting.

**Comment by mccutchen** [comment]
I _really_ like this idea, but I think it would be difficult to implement accurately and effectively while continuing to keep this project dependency-free and stateless.

It would be relatively simple to pull in something like https://pkg.go.dev/golang.org/x/time/rate as a dependency (or vendor its code) and use that to do in-process rate limiting in a single local process for use during unit or integration tests.  But, unfortunately, I do not want to add any 3rd party dependencies.

And even if we did pull something like that in, as soon as it's added to a live deployment like https://httpbingo.org, it will immediately provide inaccurate/misleading results, as live deployments are very likely to be running more than one go-httpbin process, and some shared state (often redis, or at least some knowledge of how many instances are sharing the rate limit computations) is required to make those rate limits accurate.

Given all of that, I'm inclined not to pursue this, at least for now.

I'll leave this open for a bit, in case you or other folks have ideas that I'm not thinking of that would address those concerns!

**Comment by kiblik** [comment]
Thank you, @mccutchen for your feedback.

I fully understand it would increase the complexity and become stateful especially if you run more than one instance.

I will consider preparing a similar project which will be focused only on testing rate-limits. I'm not skilled in GO yet so it might be in a different language (or I have finally reason to learn GO :) ).

I would like to include also different rate-limiting strategies and also include standards defined in the upcoming RFC https://ietf-wg-httpapi.github.io/ratelimit-headers/. 

I'm closing the issue, wish you luck with go-httpbin and hopefully I will be able to implement it in the future.

**Comment by mccutchen** [comment]
Thanks, and good luck with your project!
