### ISSUE TITLE
/bytes/0 incorrectly returns a response body of 1 byte

### ISSUE THREAD

**Issue by bneradt** [mccutchen/go-httpbin#112]
## Summary

Querying against the `/bytes/0` endpoint should return a 0 byte body, but instead returns a 1 byte body.

Tested with go-httpbin version 2.5.6:

## Reproduction Steps

go-httpbin Server:

```
$  go-httpbin -host 127.0.0.1 -port 61000
go-httpbin listening on http://127.0.0.1:61000
time="2023-02-28T17:36:51.9741" status=200 method="GET" uri="/bytes/0" size_bytes=1 duration_ms=0.12 user_agent="curl/7.85.0-DEV" client_ip=127.0.0.1:55130                                                                                                                                                       
```

Curl client:

```
$  curl -vs  http://127.0.0.1:61000/bytes/0
*   Trying 127.0.0.1:61000...
* Connected to 127.0.0.1 (127.0.0.1) port 61000 (#0)
> GET /bytes/0 HTTP/1.1
> Host: 127.0.0.1:61000
> User-Agent: curl/7.85.0-DEV
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Content-Type: application/octet-stream
< Date: Tue, 28 Feb 2023 17:36:51 GMT
< Content-Length: 1
<
* Connection #0 to host 127.0.0.1 left intact
```

Note that both go-httpbin (`size_bytes=1`) and curl (`Content-Length: 1`) indicate that go-httpbin returned a 1 byte response. The expected response would have 0 bytes.

I took a packet dump and it looks like go-httpbin is responding with a 1 byte body of value `0x48`, ascii `H`.

**Comment by bneradt** [comment]
A colleague of mine looked at the source code and found this:
https://github.com/mccutchen/go-httpbin/blob/8d82c0ddfc2c6fc3faecdfb61e104d3711683ddb/httpbin/handlers.go#L788-L789

Why is this hardcoded to 1 byte if the value is less than 1? Is that perhaps a typo and the value set at line 789 should be `0`?

**Comment by mccutchen** [comment]
Damn, it certainly looks like line 789 there is the issue.  I wish I could remember why the code is written that way, but I have no recollection.  (I'd guess maybe I took a shortcut to avoid worrying about division-by-zero in some earlier implementation of that endpoint, but that doesn't look like a danger now.

Should be a quick fix (plus a testcase), are you or your colleague interested in taking a shot at it @bneradt?  Otherwise, I'll fix this when I can.
