### ISSUE TITLE
As a developer I want to exec into the running container

### ISSUE THREAD

**Issue by a3cipher** [mccutchen/go-httpbin#121]
As a developer I want to be able to start a shell and access the container filesystem.

```shell
$ docker run --rm -it -p 8080:8080 mccutchen/go-httpbin:latest /bin/sh
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown.
```
```
$ docker run --rm -it -p 8080:8080 mccutchen/go-httpbin:latest /bin/bash
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
```

**Comment by mccutchen** [comment]
@a3cipher can you elaborate on _why_ you want to do that with this container?  I'm curious about your use case and whether there are any updates we can make to the existing image to address your needs.

That being said, at this point we're unlikely to move away from the "distroless" image we're building, so you might have to build your own image.

**Comment by mccutchen** [comment]
Gonna close this for now.  Please feel free to re-open with more context!
