### ISSUE TITLE
expect: 100-continue is not handled

### ISSUE THREAD

**Issue by bneradt** [mccutchen/go-httpbin#129]
We're using go-httpbin as a part of our tests in [apache/trafficserver](https://github.com/apache/trafficserver). We noticed a difference in behavior between httpbin.org and go-httpbin with respect to `Expect: 100-continue`:

https://www.rfc-editor.org/rfc/rfc7231#section-5.1.1

Essentially, httpbin.org replies with a `100 Continue` response when the `Expect: 100-continue` header is received, while go-httpbin seems to ignore it. It could be valuable to add `Expect: 100-continue` support.

Thanks for go-httpbin. It has been helpful to us.

**Comment by mccutchen** [comment]
@bneradt I'd like to make sure we're supporting that use case as much as possible, is there any chance you can provide a minimal example that reproduces the behavior you're seeing?

We're just relying on net/http's automatic handling of `Expect: 100-continue` — which seems to work in an isolated test case (see below) — but please note that there are some requirements for that to work as expected:
- requests MUST include a non-empty body
- requests MUST include either a non-zero `Content-Length` header OR use `Transfer-Encoding: chunked` to upload the body

I tried to test current behavior using `nc`, which I think indicates that the server is behaving as expected for at least _some_ requests using `Expect: 100-continue`:

```console
$ nc localhost 8080 <<EOF
> PUT /put HTTP/1.1
> Host: localhost
> Expect: 100-continue
> Content-Length: 4
> Content-Type: text/plain
> 
> test
> EOF
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; encoding=utf-8
Date: Mon, 26 Jun 2023 18:15:22 GMT
Content-Length: 354

{
  "args": {},
  "headers": {
    "Content-Length": [
      "4"
    ],
    "Content-Type": [
      "text/plain"
    ],
    "Expect": [
      "100-continue"
    ],
    "Host": [
      "localhost"
    ]
  },
  "method": "PUT",
  "origin": "[::1]:59158",
  "url": "http://localhost/put",
  "data": "test",
  "files": null,
  "form": null,
  "json": null
}
```

(Note the `HTTP/1.1 100 Continue` followed by `HTTP/1.1 200 OK` that start off the response(s) from the server.)

**Comment by mccutchen** [comment]
@bneradt following up here, if you can provide any more context/details around your use of go-httpbin and how/where it is not behaving as expected, it would be super helpful!

I've added some additional unit tests in https://github.com/mccutchen/go-httpbin/pull/138 that give me some confidence that we're handling at least _some_ `Expect: 100-continue` requests in a reasonable way, but there's always a decent chance that I'm missing something here.

**Comment by bneradt** [comment]
> @bneradt following up here, if you can provide any more context/details around your use of go-httpbin and how/where it is not behaving as expected, it would be super helpful!
> 
> I've added some additional unit tests in #138 that give me some confidence that we're handling at least _some_ `Expect: 100-continue` requests in a reasonable way, but there's always a decent chance that I'm missing something here.

Sorry for the delay. I did some experimentation and observed that the difference is in how httpbin.org and go-httpbin behave when an `Expect: 100-continue` header is received **with a 0-byte body**. httpbin.org replies with a `100 Continue` response whereas go-httpbin simply ignores the `Expect: 100-continue` and replies immediately with a `200 OK` (which is consistent with your initial comment in this issue). 

Spec 7231 explicitly says that go-httpbin's behavior is acceptable:

>   o  A server MAY omit sending a 100 (Continue) response if it has
      already received some or all of the message body for the
      corresponding request, or if the framing indicates that there is
      no message body.

So I don't think go-httpbin needs any update for this. The fact is my application under test needs, in this case, a server that replies with a `100 Continue` response anyway, which is also allowable by the spec, but it's unreasonable to expect go-httpbin to change for this. I plan to use [yahoo/proxy-verifier](https://github.com/yahoo/proxy-verifier) for my needs.

Thank you for your thorough response and follow up. I recommend closing this issue because go-httpbin is behaving fine and getting it to behave differently is neither necessary nor worth it.

**Comment by mccutchen** [comment]
👍 thanks for the investigation and follow-up.  I'm sorry go-httpbin won't actually meet your needs in this case, but I agree that it's not worth the effort to try accommodate this edge case.

The gift and curse of building on Go's stdlib the way we do is that it takes care of most of these details mostly correctly at a high level, but it often does not provide any useful way to customize the behavior in situations like this.

Godspeed and good luck!
