### ISSUE TITLE
Not compatible with Go 1.11 modules

### ISSUE THREAD

**Issue by akabos** [mccutchen/go-httpbin#13]
go.mod:
```
...
require (
	github.com/mccutchen/go-httpbin v2.1.0
)
```

```
$ go mod verify
go: finding github.com/mccutchen/go-httpbin v2.1.0
go: errors parsing go.mod:
[path redacted]/go.mod:5: invalid module version "v2.1.0": unknown revision v2.1.0
```

Removing `v` prefix from version fixes situation just partially.  `go mod verify` Succecedes on finding version but the next call of `go mod tidy` resets requirement to latest revision on master branch:

```
$ go mod verify
go: finding github.com/mccutchen/go-httpbin 2.1.0
all modules verified
$ go mod tidy
$ cat go.mod|grep httpbin
	github.com/mccutchen/go-httpbin v0.0.0-20190116014521-c5cb2f4802fa
```

My guess is `go mod` expects version tags to have `v` prefix which is missing here.

**Comment by mccutchen** [comment]
Ahhh good catch!  It's unfortunate that the tags I've been using up to this point don't work with `go mod` out of the box, but I can adjust them going forward.

I'll push out a quick tag bump this afternoon or tomorrow!

**Comment by mccutchen** [comment]
@akabos sorry for the delay!  I just pushed out `v`-prefixed tags for each existing prefix-less tag.  

Now, when playing around with a small test case (create `main.go` importing `github.com/mccutchen/go-httpbin`, then running `go mod init testpkg; go mod verify; go mod tidy`), the tooling picks version `v1.1.1`:

```
$ go mod tidy
go: finding github.com/mccutchen/go-httpbin/httpbin latest
$ cat go.mod 
module testpkg

require github.com/mccutchen/go-httpbin v1.1.1
```

If I explicitly specify `v2.1.0`, I end up back in the same "versionless" requirement in `go.mod`:

```
$ go get -v github.com/mccutchen/go-httpbin@v2.1.0
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
$ cat go.mod
module testpkg

require github.com/mccutchen/go-httpbin v0.0.0-20190116014521-c5cb2f4802fa
```

After digging through the wiki page, I noticed this crucial and incredibly annoying piece of information:

<img width="737" alt="screen shot 2019-02-18 at 4 52 40 pm" src="https://user-images.githubusercontent.com/57938/52982976-c042dc00-339d-11e9-9f1c-967c7d473c47.png">

(Source: https://github.com/golang/go/wiki/Modules#semantic-import-versioning)

That means this repo is in a semi broken state w/r/t go modules until I make more invasive changes.

**Comment by mccutchen** [comment]
It has taken an embarrassingly long time, but this should now be fixed, unless I've screwed up something else.  Import paths and `go get` now need to include `/v2`, e.g.

```diff
-import "github.com/mccutchen/go-httpbin/httpbin"
+import "github.com/mccutchen/go-httpbin/v2/httpbin"
```
