### ISSUE TITLE
Help with hosting

### ISSUE THREAD

**Issue by buger** [mccutchen/go-httpbin#136]
Hello! 

Availability of httpbin was not that great recently, and seems like it not really maintained.
We were looking for alternatives and go-httpbin looks great!

We need to have some service for our demos, for doing various tests, offer it as test url for our trial user first experience, right in UI etc. 

Initially we wanted to have it hosted just under our own domain like httpbin.tyk.io, so we can ensure quality of its availability, but I wonder if we can just offer you help of hosting your service https://httpbingo.org, and take care of its availability?

Cheers!

**Comment by mccutchen** [comment]
> Initially we wanted to have it hosted just under our own domain like httpbin.tyk.io, so we can ensure quality of its availability, but I wonder if we can just offer you help of hosting your service https://httpbingo.org, and take care of its availability?

To be clear, are you offering to take on responsibility for hosting the service running at [httpbingo.org](https://httpbingo.org) yourself, or offering to contribute financially to offset the costs I incur running that service, or something else?

Right now, [httpbingo.org](https://httpbingo.org) costs me nothing (aside from sporadic and minimal labor), as it is running on [Fly.io](https://fly.io)'s free tier.  As you can imagine — and maybe have already observed yourself — I offer no guarantees for its availability or reliability.

And, to be totally honest, I'm not particularly interested in any arrangement where I'd be on the hook for the availability/reliability of a public instance; I'm not interested in a solo 24/7/365 on-call rotation for a side project.

All that being said, I would love to hear more about your needs and use cases!  It should be pretty trivial to spin up your own instances on basically any deployment platform that can run a docker image; the service and the published docker images are designed to make that as easy as possible.

**Comment by mccutchen** [comment]
In case it's helpful, the [mccutchen/httpbingo.org](https://github.com/mccutchen/httpbingo.org) repo contains the actual source code and configuration for the httpbingo.org deployment; it is basically just a codification of the [Production considerations](https://github.com/mccutchen/go-httpbin#production-considerations) section of go-httpbin's README.

**Comment by mccutchen** [comment]
(Also, please feel free to reach out to me directly at <my first name> @ mccutch.org if you'd rather continue this conversation outside of GitHub issues!)

**Comment by mccutchen** [comment]
Closing for now.
