### ISSUE TITLE
Enable all Methods on basic-auth

### ISSUE THREAD

**Issue by mgeuer** [mccutchen/go-httpbin#163]
Can we enable basic auth for all methods (GET, POST, PUT, DELETE, PATCH) by adding all methods on httpbin:
`mux.HandleFunc("/basic-auth/", methods(h.BasicAuth, "GET", "POST", "PUT", "DELETE", "PATCH"))`

**Comment by mccutchen** [comment]
Sure, seems like a good addition!  Want to open a PR?

**Comment by mccutchen** [comment]
Fixed in #166
