### ISSUE TITLE
Timeouts etc. on httpbingo.org

### ISSUE THREAD

**Issue by tommaisey** [mccutchen/go-httpbin#176]
In the last 2-3 days we've been seeing quite a few instances of timeouts, 'no reply', incomplete bodies and other stuff when accessing the `httpbingo.org` API, causing most of our CI runs to fail. Just thought I'd note here in case there's DDOSing or anything like that causing these issues.

**Comment by mccutchen** [comment]
Thanks for the report.  It looks like there has been intermittent excessive traffic from a particular user agent, so I've deployed a quick and dirty fix (see https://github.com/mccutchen/httpbingo.org/issues/4).

That being said, the httpbingo.org service offers absolutely zero guarantees about uptime or reliability.  It's hosted on [Fly.io](https://fly.io/)'s free tier, and I do not plan to spend any of my own money on hosting costs.

If your company wants reliable CI runs, you'd be much better off spinning up a local instance on your CI machine (or somewhere in your own infrastructure) and pointing your tests at that!  That can be as simple as

```
docker run -p 8080:8080 mccutchen/go-httpbin:v2.14.0
```

If you have any questions about the best way to integrate a local instance of go-httpbin into your CI process, I'd be happy to discuss!
