### ISSUE TITLE
returned URL now has internal host/port

### ISSUE THREAD

**Issue by ddebrunner** [mccutchen/go-httpbin#187]
A request like: https://httpbingo.org/get?v=New+York

use to return URL as:

```
"url": "https://httpbingo.org/get?v=New+York"
```

but now has:

```
"url": "https://172.19.134.10:8080/get?v=New+York"
```

Is this intentional?

**Comment by mccutchen** [comment]
Nope, definitely not intentional!  Might be related to this recent change to the project that defines the instance of go-httpbin deployed at https://httpbingo.org:
https://github.com/mccutchen/httpbingo.org/pull/6

Thanks for the report, lemme look into this!
