### ISSUE TITLE
无法拉取镜像，是arm64的机器

### ISSUE THREAD

**Issue by wwhwwxlz** [mccutchen/go-httpbin#193]
[root@master go-httpbin]# make image
DOCKER_BUILDKIT=1 docker build -t mccutchen/go-httpbin:ce8d747 .
[+] Building 90.3s (2/2) FINISHED                                                         docker:default
 => [internal] load build definition from Dockerfile                                                0.2s
 => => transferring dockerfile: 457B                                                                0.0s
 => ERROR resolve image config for docker-image://docker.io/docker/dockerfile:1.3                  90.0s
------
 > resolve image config for docker-image://docker.io/docker/dockerfile:1.3:
------
Dockerfile:1
--------------------
   1 | >>> # syntax = docker/dockerfile:1.3
   2 |     FROM golang:1.23 AS build
   3 |
--------------------
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: failed to resolve source metadata for docker.io/docker/dockerfile:1.3: failed to do request: Head "https://registry.hub.docker.com/v2/docker/dockerfile/manifests/1.3?ns=docker.io": dial tcp 31.13.87.19:443: i/o timeout
make: *** [Makefile:92: image] Error 1

**Comment by mccutchen** [comment]
Hi, this looks to be a network issue or potentially a Docker Hub availability issue, not something specific to this project. 

Can you try again from a different network or a different computer?
