### ISSUE TITLE
Add unusual behaviour endpoints

### ISSUE THREAD

**Issue by prune998** [mccutchen/go-httpbin#34]
Hi there,

I build a dumb (quick) web server like httpbin that (for the moment) mostly reply with malformed data. It was really useful to me to tests some scenarios. 
For the moment, I have:
- send data before headers
- send duplicate headers
- delay answer

I also plan to add some ping/pong GRPC endpoint (It may break your `only require http package` ).

I was wondering if that could be of interest if I made a PR (after a rewrite to compete with your clean code) or if i'm better fork your code and live on my own ?

Thanks

**Comment by mccutchen** [comment]
@prune998 👋 hi! I think some intentionally malformed endpoints make sense, I’d definitely welcome a PR for that!

On the other hand, I’m not really interested in pulling in all the machinery necessary to expose example gRPC endpoints.

**Comment by prune998** [comment]
GRPC could be another project then... but with go modules it's easy to pull needed packages :)
I'll see to make a PR soon. Thanks for fast answer

**Comment by mccutchen** [comment]
I'm going to close this for now.  We're not going to add anything gRPC-related and we'd have to fight too hard against the stdlib http server implementation to do anything particularly interesting in terms of mal-formed responses.
