### ISSUE TITLE
httpbingo.org: HTTP redirects to HTTPS

### ISSUE THREAD

**Issue by splitbrain** [mccutchen/go-httpbin#35]
httpbingo.org currently redirects all requests form HTTP to HTTPS, making explicit HTTP tests impossible. For maximum compatibility with httpbin.org it should answer in exactly the protocol that was requested.

**Comment by mccutchen** [comment]
Ah, yeah, that makes sense, thanks for opening this!  Lemme see if I can fix this quickly, semi-opaque App Engine configuration gods willing.

**Comment by mccutchen** [comment]
@splitbrain thanks again for the report, this should be fixed as of #36.  Lemme know if it works for you!
