### ISSUE TITLE
httpbingo.org down?

### ISSUE THREAD

**Issue by stefan-guggisberg** [mccutchen/go-httpbin#51]
Hi @mccutchen, first of all thanks for this great project! I am using it in tests in the https://github.com/adobe/helix-fetch project.

I noticed that `https://httpbingo.org` is not reachable anymore. Is this temporary?

**Comment by mccutchen** [comment]
Uh oh, https://httpbingo.org/ definitely should be up!  When you say "not reachable," what does that mean?  Are you getting connection timeouts?  Do you know how long it has been down?

If it's still down for you, can post the output of a verbose curl command like this one?  It might help diagnose the problem.

```
curl -v -s --max-time 5 https://httpbingo.org/ >/dev/null
```

On my end, I use the free tier of [Uptime Robot](https://uptimerobot.com/) to monitor https://httpbingo.org's availability.  At 5 minute intervals, its granularity is far from perfect, but it should let me know if there are extended outages.  It shows no recent issues:

![Screenshot_2021-03-02 Dashboard UptimeRobot](https://user-images.githubusercontent.com/57938/109728154-a8ed7a80-7b83-11eb-9419-d0293d266620.png)

**Comment by stefan-guggisberg** [comment]
Thanks Will, it's working again for me. Yesterday I got persistent DNS lookup errors:

```
getaddrinfo ENOTFOUND httpbingo.org
``` 

and `This site can't be reached` in the browser (Chrome). The only site I've got this error. All other sites were working as expected. 

(sorry, should have been more precise)

Maybe a temporary DNS sync issue? However, I am glad it's working again. Thanks!

**Comment by mccutchen** [comment]
Closing for now.  Will need to figure out how to stay on top of issues like this, and possibly consider another provider at some point.  Thanks again for the report!
