### ISSUE TITLE
Provide request forwarding capability

### ISSUE THREAD

**Issue by neowulf** [mccutchen/go-httpbin#52]
Rather than using the redirect and having the client make another request to the new url - provide another endpoint which will forward the original request to the provided url.

**Comment by mccutchen** [comment]
I’m not sure I understand what exactly the proposed endpoint would do, would you mind explaining with a bit more detail?

It seems like you’re describing an endpoint that would effectively act as a proxy for arbitrary 3rd party URLs, and that’s not something I’m particularly interested in adding, as it seems like a possible vector for abuse.
