### ISSUE TITLE
new endpoint suggestion - /intermittent

### ISSUE THREAD

**Issue by gurgeous** [mccutchen/go-httpbin#53]
Love httpbingo & httpbingo.org, thanks for creating! How about an endpoint that fails intermittently? That would be handy for testing retries and such. Perhaps `/intermittent` fails 75% of the time, returning HTTP 500?

**Comment by gurgeous** [comment]
Or perhaps '/unstable'

**Comment by mccutchen** [comment]
I like this idea in general, want to take a pass at implementation?

**Comment by gurgeous** [comment]
Yes, definitely! I've written some go, though I wouldn't call myself an expert. Should be easy. Any other endpoints you want to consider as long as I'm in there?

**Comment by mccutchen** [comment]
Cool!  In terms of design, I think I'm partial to your second suggestion: `/unstable`

I imagine it might take a parameter controlling failure rate as a float, maybe `failure_rate`, in the range [0,1], with a default of 0.5?

**Comment by mccutchen** [comment]
Closed by #54
