### ISSUE TITLE
Support for PATCH method

### ISSUE THREAD

**Issue by marianopeck** [mccutchen/go-httpbin#59]
Hi, I don't seem to find an option to test the PATCH method as [the old httpbin had](https://httpbin.org/#/HTTP_Methods/patch_patch).
Is it available somehow?

Thanks

**Comment by mccutchen** [comment]
There's a `/patch` endpoint that works the way python httpbin's does, AFAIK.  Try something like this:

```
curl -s -X PATCH -d '{"id": 12345}' -H "Content-Type: application/json" https://httpbingo.org/patch
```

It is definitely missing from the list of endpoints on the home page, as are the endpoints for other HTTP verbs aside from `/get`.  The main reason for that is that you can't click a link to the `/patch` (or `/post` or `/put` etc) endpoints and have them work, you'll just get an unfriendly 

```
method GET not allowed
```

error message.

I should still add them to the index somehow.  Thanks for the report!

**Comment by marianopeck** [comment]
Thanks for the quick response!  Excellent news it is supported. I thought it wasn't because indeed I didn't see it in the homepage. (same for `PUT` and the rest of the methods)
