### ISSUE TITLE
Missing features compared to httpbin.org

### ISSUE THREAD

**Issue by na--** [mccutchen/go-httpbin#6]
The following [httpbin.org](https://httpbin.org/) features (besides `/brotli`) are not present in the library:
- `now.httpbin.org The current time, in a variety of formats.` (this probably will be more useful as a `/now` url...)
- `/uuid Returns UUID4.`
- `/anything Returns request data, including method used.`
- `/anything/:anything Returns request data, including the URL.`
- `/base64/:value Decodes base64url-encoded string.`

None of them are a big deal, just posting this for completion. If I have the time, I may implement some of them, though I doubt that will be very soon.

**Comment by Integralist** [comment]
Ah yeah I see a whole truckload of cool features in official website version. Would be great to see this back ported. @mccutchen maybe a hack week project for me 🙂

**Comment by mccutchen** [comment]
@Integralist go for it!  A pile of new endpoints have been added recently by @saurabh-hirani:

 - /bearer added in #21 
 - /json added in #20 
 - /base64 added in #18 
 - /uuid added in #16

**Comment by saurabh-hirani** [comment]
@Integralist  - go-httpbin handler and testing code is very well thought out - thanks to @mccutchen
 As per https://github.com/postmanlabs/httpbin/blob/master/httpbin/core.py - we are almost feature complete - save for the /anything endpoint. I was going to work on it over the coming weekend. If you are interested in picking it up, bump this comment up.

**Comment by Integralist** [comment]
I ♥️ the `/anything` endpoint. I'm on leave for a few weeks but when I'm back it will be just in time for hack week 😀

**Comment by mccutchen** [comment]
I'm going to call this one done, for now.  Everything but `time.httpbin.org` has been implemented, and we can use #91 to track any other incompatibilities/missing features/etc.

**Comment by mccutchen** [comment]
> I'm going to call this one done, for now. Everything but `time.httpbin.org` has been implemented, and we can use #91 to track any other incompatibilities/missing features/etc.

Turns out I missed a relatively big one that is now being addressed: https://github.com/mccutchen/go-httpbin/pull/123
