### ISSUE TITLE
Add option to enable verbose request/response logging

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [mccutchen/go-httpbin#62]
Could you help to add a `-v` option to make httpbin output detailed request and response information (like `curl -v`)? That would make the program more useful. I searched around and found that the [httputil package](https://golang.org/pkg/net/http/httputil/) has `DumpRequest` and `DumpResponse` methods, which could be used for this feature. 

Btw, thanks for creating such a useful tool!

**Comment by mccutchen** [comment]
@0x7FFFFFFFFFFFFFFF I'd be interested to see what this would look like, if you wanted to take a pass at an implementation.  I think that dumping responses could be a bit tricky for at least those endpoints that stream data back to the client.

**Comment by mccutchen** [comment]
I'm going to consider this one closed by https://github.com/mccutchen/go-httpbin/pull/109.

@0x7FFFFFFFFFFFFFFF please feel free to reopen with more context if that endpoint doesn't meet your needs!
