### ISSUE TITLE
can you push multi-arch images to docker-hub?

### ISSUE THREAD

**Issue by danbf** [mccutchen/go-httpbin#63]
![200 (2)](https://user-images.githubusercontent.com/5041307/126233432-014a1f34-5b9d-4973-a19d-a00e11fb35aa.gif)

do you think you can start pushing multi-arch images to docker-hub ala'
```
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7
```

https://www.docker.com/blog/multi-arch-images/

**Comment by mccutchen** [comment]
👋 hey @danbf!

![name](https://user-images.githubusercontent.com/57938/126234132-e07169c0-0f12-4ece-a6eb-eeabf868c22d.gif)

I could probably do something like that … I need to automate release builds on merge, might as well push up multi-arch builds while I'm at it.  Do you have a particular need for each of those architectures?  (Left to my own devices, I'd probably just stick to `linux/amd64` and `linux/arm64` as the most likely architectures.)

**Comment by danbf** [comment]
glad to see you are still finding time for maintaining this 😄 

it's hackweek and i'm doing rig on arm, which is turning out to be surprisingly easy, and almost certainly going to go into production. for that `linux/amd64` and `linux/arm64` seems to satisfy aws ecs's mix of regular and graviton's.  `linux/arm/v7` seems to be mostly used by the pi folk.

no rush.  should be pretty straightforward since your upstream is already multi-arch.

**Comment by mccutchen** [comment]
@danbf while I figure out how best to automate this, I just manually built and pushed a multi-arch build to the tag `mccutchen/go-httpbin:v2.2.2-multiarch`:

<img width="914" alt="Screen Shot 2021-07-21 at 10 29 23 AM" src="https://user-images.githubusercontent.com/57938/126506058-21fbc1e3-6b1d-4883-876e-399a6bc2efb2.png">

Lemme know if that works for you!

**Comment by danbf** [comment]
![giphy (6)](https://user-images.githubusercontent.com/5041307/126573268-250efc73-6688-44a4-b16c-620231c7503b.gif)

double awesome with a cherry on top.

**Comment by danbf** [comment]
since buildx needs some setup, i do this on my end for mult-arch's

ensure i cleared out the buildx builder in case it got interrupted before
```
docker buildx rm <builder-name>
```
then:
```
docker buildx create --name <builder-name>
docker buildx use <builder-name>
docker buildx build --tag <remote_tag> . --platform linux/amd64,linux/arm64,linux/arm/v7 --push
```
then clear out the buildx builder so it's ready for the next time i run it
```
docker buildx rm <builder-name>
```

**Comment by danbf** [comment]
totally works, checkout the hostname in the log rig-unstable-ecs-`graviton`-writative-abandonedly :

```
{
  "id": "AQAAAXrLnDPnaXCq8wAAAABBWHJMbkRQOUFBQ3NYa3dteVBkdm13QUY",
  "content": {
    "host": "rig-unstable-ecs-graviton-writative-abandonedly",
    "service": "httpbin",
    "message": "time=\"2021-07-22T00:27:29.5737\" status=200 method=\"GET\" uri=\"/cookies\" size_bytes=2 duration_ms=0.04",
    "attributes": {
      "rig": {
        "cluster": "unstable",
        "service": "httpbin",
        "deployment_type": "primary"
      },
      "level": "info",
      "hostname": "rig-unstable-ecs-graviton-writative-abandonedly",
      "message": "time=\"2021-07-22T00:27:29.5737\" status=200 method=\"GET\" uri=\"/cookies\" size_bytes=2 duration_ms=0.04",
      "cluster": "unstable",
      "datadog-agent-status": "info"
    }
  }
}
```

**Comment by danbf** [comment]
we've also confirmed this works for Apple M1 machines.
