### ISSUE TITLE
Docker Tag v2.4.0

### ISSUE THREAD

**Issue by khmarbaise** [mccutchen/go-httpbin#80]
I would like to know if it would be possilbe to create a version of the docker image with version 2.4.0 because a git tag already exists.

Can I support in any way to help here?

**Comment by mccutchen** [comment]
Thanks for the reminder, I'm sorry I missed this!  Image `mccutchen/go-httpbin:v2.4.0` is [now available](https://hub.docker.com/layers/go-httpbin/mccutchen/go-httpbin/v2.4.0/images/sha256-8f68c60af5916972ce18f225a5dfae3378fa344f10f1e5d14baf759ee9d90833?context=explore) (and `:latest` was also pushed to match).

I need to take some time and wire up a GitHub Action to build & push when I stamp a new release, just haven't had the time to do that yet.

**Comment by khmarbaise** [comment]
Great to hear. Many thanks for your work. No need to apologize.
