### ISSUE TITLE
Do not hardcode logger

### ISSUE THREAD

**Issue by sagikazarmark** [mccutchen/go-httpbin#9]
This library is a great candidate for integration into custom applications for testing purposes. Unfortunately it hardcodes the global logger which makes using it harder.

**Comment by mccutchen** [comment]
Good suggestion, thanks @sagikazarmark!  Does #11 meet your needs, or did you have a different implementation in mind?

**Comment by sagikazarmark** [comment]
Answered on the PR. Thanks for the quick answer!
